# Generated by Django 3.1.5 on 2021-01-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_reserve'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
