# Generated by Django 3.1.5 on 2021-01-15 14:53

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20210113_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='location',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
